# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30e54d67c977f5e2299f2107d0447541e8bd6ac0739e2c8b5e27b01316772c9afbd980f9c3ab371aae8ca8d14a01174b2e236fb3d02a25d103253a5465621535

test:
  secret_key_base: 413d3d5cc6d086e458bf69ce93ab3a8e921dd2383c5e59d3545565bafa5037bc08846040ea61c30e414c0d9003ec1dad20bbad00a9a328e9e9972542708a3911

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
